require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HackplatformrelationsController do

  # This should return the minimal set of attributes required to create a valid
  # Hackplatformrelation. As you add validations to Hackplatformrelation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all hackplatformrelations as @hackplatformrelations" do
      hackplatformrelation = Hackplatformrelation.create! valid_attributes
      get :index
      assigns(:hackplatformrelations).should eq([hackplatformrelation])
    end
  end

  describe "GET show" do
    it "assigns the requested hackplatformrelation as @hackplatformrelation" do
      hackplatformrelation = Hackplatformrelation.create! valid_attributes
      get :show, :id => hackplatformrelation.id
      assigns(:hackplatformrelation).should eq(hackplatformrelation)
    end
  end

  describe "GET new" do
    it "assigns a new hackplatformrelation as @hackplatformrelation" do
      get :new
      assigns(:hackplatformrelation).should be_a_new(Hackplatformrelation)
    end
  end

  describe "GET edit" do
    it "assigns the requested hackplatformrelation as @hackplatformrelation" do
      hackplatformrelation = Hackplatformrelation.create! valid_attributes
      get :edit, :id => hackplatformrelation.id
      assigns(:hackplatformrelation).should eq(hackplatformrelation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hackplatformrelation" do
        expect {
          post :create, :hackplatformrelation => valid_attributes
        }.to change(Hackplatformrelation, :count).by(1)
      end

      it "assigns a newly created hackplatformrelation as @hackplatformrelation" do
        post :create, :hackplatformrelation => valid_attributes
        assigns(:hackplatformrelation).should be_a(Hackplatformrelation)
        assigns(:hackplatformrelation).should be_persisted
      end

      it "redirects to the created hackplatformrelation" do
        post :create, :hackplatformrelation => valid_attributes
        response.should redirect_to(Hackplatformrelation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hackplatformrelation as @hackplatformrelation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hackplatformrelation.any_instance.stub(:save).and_return(false)
        post :create, :hackplatformrelation => {}
        assigns(:hackplatformrelation).should be_a_new(Hackplatformrelation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hackplatformrelation.any_instance.stub(:save).and_return(false)
        post :create, :hackplatformrelation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hackplatformrelation" do
        hackplatformrelation = Hackplatformrelation.create! valid_attributes
        # Assuming there are no other hackplatformrelations in the database, this
        # specifies that the Hackplatformrelation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hackplatformrelation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => hackplatformrelation.id, :hackplatformrelation => {'these' => 'params'}
      end

      it "assigns the requested hackplatformrelation as @hackplatformrelation" do
        hackplatformrelation = Hackplatformrelation.create! valid_attributes
        put :update, :id => hackplatformrelation.id, :hackplatformrelation => valid_attributes
        assigns(:hackplatformrelation).should eq(hackplatformrelation)
      end

      it "redirects to the hackplatformrelation" do
        hackplatformrelation = Hackplatformrelation.create! valid_attributes
        put :update, :id => hackplatformrelation.id, :hackplatformrelation => valid_attributes
        response.should redirect_to(hackplatformrelation)
      end
    end

    describe "with invalid params" do
      it "assigns the hackplatformrelation as @hackplatformrelation" do
        hackplatformrelation = Hackplatformrelation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hackplatformrelation.any_instance.stub(:save).and_return(false)
        put :update, :id => hackplatformrelation.id, :hackplatformrelation => {}
        assigns(:hackplatformrelation).should eq(hackplatformrelation)
      end

      it "re-renders the 'edit' template" do
        hackplatformrelation = Hackplatformrelation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hackplatformrelation.any_instance.stub(:save).and_return(false)
        put :update, :id => hackplatformrelation.id, :hackplatformrelation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hackplatformrelation" do
      hackplatformrelation = Hackplatformrelation.create! valid_attributes
      expect {
        delete :destroy, :id => hackplatformrelation.id
      }.to change(Hackplatformrelation, :count).by(-1)
    end

    it "redirects to the hackplatformrelations list" do
      hackplatformrelation = Hackplatformrelation.create! valid_attributes
      delete :destroy, :id => hackplatformrelation.id
      response.should redirect_to(hackplatformrelations_url)
    end
  end

end
