require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserhackrelationsController do

  # This should return the minimal set of attributes required to create a valid
  # Userhackrelation. As you add validations to Userhackrelation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all userhackrelations as @userhackrelations" do
      userhackrelation = Userhackrelation.create! valid_attributes
      get :index
      assigns(:userhackrelations).should eq([userhackrelation])
    end
  end

  describe "GET show" do
    it "assigns the requested userhackrelation as @userhackrelation" do
      userhackrelation = Userhackrelation.create! valid_attributes
      get :show, :id => userhackrelation.id
      assigns(:userhackrelation).should eq(userhackrelation)
    end
  end

  describe "GET new" do
    it "assigns a new userhackrelation as @userhackrelation" do
      get :new
      assigns(:userhackrelation).should be_a_new(Userhackrelation)
    end
  end

  describe "GET edit" do
    it "assigns the requested userhackrelation as @userhackrelation" do
      userhackrelation = Userhackrelation.create! valid_attributes
      get :edit, :id => userhackrelation.id
      assigns(:userhackrelation).should eq(userhackrelation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Userhackrelation" do
        expect {
          post :create, :userhackrelation => valid_attributes
        }.to change(Userhackrelation, :count).by(1)
      end

      it "assigns a newly created userhackrelation as @userhackrelation" do
        post :create, :userhackrelation => valid_attributes
        assigns(:userhackrelation).should be_a(Userhackrelation)
        assigns(:userhackrelation).should be_persisted
      end

      it "redirects to the created userhackrelation" do
        post :create, :userhackrelation => valid_attributes
        response.should redirect_to(Userhackrelation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved userhackrelation as @userhackrelation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Userhackrelation.any_instance.stub(:save).and_return(false)
        post :create, :userhackrelation => {}
        assigns(:userhackrelation).should be_a_new(Userhackrelation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Userhackrelation.any_instance.stub(:save).and_return(false)
        post :create, :userhackrelation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested userhackrelation" do
        userhackrelation = Userhackrelation.create! valid_attributes
        # Assuming there are no other userhackrelations in the database, this
        # specifies that the Userhackrelation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Userhackrelation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => userhackrelation.id, :userhackrelation => {'these' => 'params'}
      end

      it "assigns the requested userhackrelation as @userhackrelation" do
        userhackrelation = Userhackrelation.create! valid_attributes
        put :update, :id => userhackrelation.id, :userhackrelation => valid_attributes
        assigns(:userhackrelation).should eq(userhackrelation)
      end

      it "redirects to the userhackrelation" do
        userhackrelation = Userhackrelation.create! valid_attributes
        put :update, :id => userhackrelation.id, :userhackrelation => valid_attributes
        response.should redirect_to(userhackrelation)
      end
    end

    describe "with invalid params" do
      it "assigns the userhackrelation as @userhackrelation" do
        userhackrelation = Userhackrelation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Userhackrelation.any_instance.stub(:save).and_return(false)
        put :update, :id => userhackrelation.id, :userhackrelation => {}
        assigns(:userhackrelation).should eq(userhackrelation)
      end

      it "re-renders the 'edit' template" do
        userhackrelation = Userhackrelation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Userhackrelation.any_instance.stub(:save).and_return(false)
        put :update, :id => userhackrelation.id, :userhackrelation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested userhackrelation" do
      userhackrelation = Userhackrelation.create! valid_attributes
      expect {
        delete :destroy, :id => userhackrelation.id
      }.to change(Userhackrelation, :count).by(-1)
    end

    it "redirects to the userhackrelations list" do
      userhackrelation = Userhackrelation.create! valid_attributes
      delete :destroy, :id => userhackrelation.id
      response.should redirect_to(userhackrelations_url)
    end
  end

end
